### ISSUE TITLE
is it possible to set perpagesize into [10, 25, 50, 100, **ALL**]

### ISSUE THREAD

**Issue by paul-cylix** [uwla/vue-data-table#64]
Hello sir Andre, first of all this is not an issue this is just a question.

I just want to ask if it is possible to set perpagesize into [10, 25, 50, 100, **ALL**]
because i have a dynamic data and sometimes it exceeds the given size per page.
i am using the export to csv but it limits the row of data that i wanna export.
right now i am using **perpagesize =  [10, 25, 50, 100, 10000]** since i my data doesn't exceed 10000.

Hope you can help me again. thank you :)

**Comment by AndreSouzaAbreu** [comment]
Hello!

Yes, this is indeed possible!

Just pass a dynamic value for `perPageSizes`, like as follows:

```vue
<template>
    <div>
        <h1>Dashboard</h1>
        <data-table v-bind="bindings"/>
    </div>
</template>
<script>
export default {
    computed: {
        perPageSizes() {
            // round `length` to the closest multiple of 100
            // for example, `length` = 743 means `fullSize` = 800
            let fullSize = 100 * Math.ceil(this.myData.length/100);

            // return the result
            return [10, 20, 50, fullSize]
        },
        bindings() {
            return {
                columns: [ /*the columns*/ ]
                data: this.myData,
                perPageSizes: this.perPageSizes,
            }
        }
    },
}
</script>
```

I think this solves your problem

**Comment by uwla** [comment]
Now, I recognize my proposed solution is not good.

Indeed, it is better to have a "SHOW ALL" option instead of setting the perpages sizes.
I will add it.

**Comment by uwla** [comment]
@paul-cylix this feature has been added to the latest branch and will be available soon in the next release. I'll just add some more tests before publishing a new release. Thanks for helping improving the project. I hope this plugin has been helpful!
