### ISSUE TITLE
How to use the action buttons with vue 2

### ISSUE THREAD

**Issue by jesusran06** [uwla/vue-data-table#78]

**Comment by uwla** [comment]
Hi!

Many people have asked this same question before...
For example https://github.com/uwla/vue-data-table/issues/62

How to use action buttons is explained in the README.
Basically, you can provide a custom Vue component to render inside a table cell.

In the past, this plugin  provided  its  own  *action  buttons*,  but  this  was
somewhat restrictive. I decided to give developers more control and  flexibility
by giving them the ability to provide their own components.

That way, you as developer have full control  on  how  the  button  should  look
like, as well as how to handle JS events such as onClick.
